texture_prefetch(spr_shipping_label);
depth = -999; // Fricken HTML

names_first =
[
	"John",
	"Joseph",
	"Jeff",
	"Jane",
	"Janis",
	"Judith",
	"Aaron",
	"Adam",
	"Aris",
	"Caleb",
	"Beatrice",
	"Madison",
	"James",
	"Noah",
	"Nolan",
	"Glenn",
	"Lexi",
	"Lena",
	"Lori",
	"Laura",
	"Denis",
	"Denise",
	"Zelda",
	"Link",
	"Layla",
	"Navia",
	"Carlotta",
	"Brant",
	"Michael",
	"Kayla",
	"Karla",
	"Carla",
	"Carl",
	"Mina",
	"Mita",
	"Jonathan",
	"Ben",
	"Benjamin",
	"Lyle",
	"Walter",
	"Jesse",
	"Jessie",
	"Gordon",
	"Gabriel",
	"Gabriella",
	"Oliver",
	"Olivia",
	"Grace",
	"Rita",
	"Caroline",
	"Carol",
	"Avery",
	"Andrew",
	"Chaya",
	"Ethan",
	"Mary",
	"Burnice",
	"Bernice",
	"Bronya",
	"Samuel",
	"Samantha",
	"April",
	"June",
	"Kimberly",
	"Ellen",
	"Belle",
	"Ruby",
	"Rose",
	"Welt",
	"Charlotte",
	"Lynette",
	"Lyney",
	"Lenard",
	"Robert",
	"Daniel",
	"Sara",
	"Sarah",
	"Alya",
	"Alissa",
	"Alyssa",
	"Demitri",
	"Regina"
];

names_last =
[
	"Anderson",
	"Brisker",
	"Black",
	"Williams",
	"Brown",
	"Jones",
	"Garcia",
	"Mills",
	"Miller",
	"Davis",
	"Thomas",
	"Thompson",
	"Moore",
	"Moorse",
	"Jackson",
	"Clark",
	"Young",
	"Scott",
	"Flores",
	"Montelli",
	"Goodman",
	"Pinkman",
	"White",
	"Nguyen",
	"Evans",
	"Gomez",
	"Cooper",
	"Gray",
	"Myers",
	"Simons",
	"Bell",
	"Fischer",
	"Fisher",
	"Yang",
	"Cheng",
	"Joe",
	"Ehrmantraut",
	"Buskar",
	"Skyes",
	"McGill",
	"McDonald",
	"MacDonald",
	"Freeman",
	"Wexler",
	"Lincoln",
	"Clinton",
	"Luther",
	"Rand"
];

cities =
[
	"Montgomery, AL, USA",
	"Juneau, AK, USA",
	"Phoenis, AZ, USA",
	"Little Rock, AR, USA",
	"Sacramento, CA, USA",
	"Los Angeles, CA, USA",
	"San Francisco, CA, USA",
	"Denver, CO, USA",
	"Hartford, CT, USA",
	"Dover, DE, USA",
	"Tallahassee, FL, USA",
	"Orlando, FL, USA",
	"Miami, FL, USA",
	"Atlanta, GA, USA",
	"Honolulu, HI, USA",
	"Boise, ID, USA",
	"Springfield, IL, USA",
	"Indianapolis, IN, USA",
	"Des Moines, IA, USA",
	"Topeka, KS, USA",
	"Kansas City, KS, USA",
	"Frankfort, KY, USA",
	"Lexington, KY, USA",
	"Baton Rouge, LA, USA",
	"New Orleans, LA, USA",
	"Augusta, ME, USA",
	"Annapolis, MD, USA",
	"Boston, MA, USA",
	"Lansing, MI, USA",
	"Detroit, MI, USA",
	"Saint Paul, MN, USA",
	"Jackson, MS, USA",
	"Jefferson City, MO, USA",
	"Helena, MT, USA",
	"Lincoln, NE, USA",
	"Carson City, NV, USA",
	"Las Vegas, NV, USA",
	"Concord, NH, USA",
	"Trenton, NJ, USA",
	"Santa Fe, NM, USA",
	"Albuquerque, NM, USA",
	"Albany, NY, USA",
	"New York, NY, USA",
	"Raleigh, NC, USA",
	"Bismarck, ND, USA",
	"Columbus, OH, USA",
	"Cleveland, OH, USA",
	"Cincinnati, OH, USA",
	"Oklahoma City, OK, USA",
	"Salem, OR, USA",
	"Harrisburg, PA, USA",
	"Providence, RI, USA",
	"Columbia, SC, USA",
	"Pierre, SD, USA",
	"Nashville, TN, USA",
	"Austin, TX, USA",
	"Dallas, TX, USA",
	"Houston, TX, USA",
	"Salt Lake City, UT, USA",
	"Montpelier, VT, USA",
	"Richmond, VA, USA",
	"Olympia, WA, USA",
	"Seattle, WA, USA",
	"Charleston, WV, USA",
	"Madison, WI, USA",
	"Cheyenne, WY, USA",
	"Cody, WY, USA",
	"Washington D.C., USA",
	"Mexico City, Mexico",
	"St. John's, NL, CA",
	"Charlottetown, PE, CA",
	"Halifax, NS, CA",
	"Fredericton, NB, CA",
	"Quebec City, QC, CA",
	"Toronto, ON, CA",
	"Winnipeg, MB, CA",
	"Regina, SK, CA",
	"Edmonton, AB, CA",
	"Victoria, BC, CA",
	"Iqaluit, NU, CA",
	"Yellowknife, NT, CA",
	"Whitehorse, YT, CA"
];

names_street =
[
	"Pine",
	"Little Pine",
	"Fern",
	"South",
	"Sixth",
	"Seventh",
	"Lincoln",
	"Forest",
	"Rose",
	"Flora",
	"Sunflower",
	"Poppy",
	"Merrigold",
	"West",
	"East",
	"North"
];

suffixes =
[
	"Ave",
	"Ln",
	"Rd",
	"St",
	"Dr"
];

label_name = "name";
label_address = "address";
label_city = "city";
timer_ticks = 0;

is_finished = false;

function f_create_label()
{
	var _fn = names_first[irandom_range(0, array_length(names_first) - 1)];
	var _ln = names_last[irandom_range(0, array_length(names_last) - 1)];
	
	label_name = $"{_fn} {_ln}";
	
	var _nm = irandom_range(10, 9999);
	var _ns = names_street[irandom_range(0, array_length(names_street) - 1)] ;
	var _ss = suffixes[irandom_range(0, array_length(suffixes) - 1)];
	
	label_address = $"{_nm} {_ns} {_ss}";
	
	label_city = cities[irandom_range(0, array_length(cities) - 1)];
	
	image_index = irandom_range(0, 3);
}

f_create_label();